### ISSUE TITLE
klient

### ISSUE THREAD

**Issue by LukeSQLY** [Mrucznik/mrucznik-rp-csharp#2]
to jest do odpalenia na kliencie SA:MP?

**Comment by Dawidoskyy** [comment]
xD

**Comment by Mrucznik** [comment]
Z ludźmi Twojego pokroju nie współpracuję.

**Comment by serinhoo** [comment]
krotko

**Comment by LukeSQLY** [comment]
Nie zesraj się @Mrucznik, zacznij od siebie

**Comment by Dawidoskyy** [comment]
haha luke 3 nocki teraz bedzie siedzial i kminil jak to dziala a potem wielka aktualizacja kotnik v3.0 bedzie

**Comment by LukeSQLY** [comment]
haha bo wiesz, idz zwal dupom koledze metinkowi

**Comment by Dawidoskyy** [comment]
Tak mu zazdroscisz ze maly metinek narobil tyle niedobrego dla poteznego serwisu kotnik-rp?

**Comment by LukeSQLY** [comment]
mały metinek to niech idzie sobie na nodze kutasa narysować, pozdruwka nara zjedz mi chuj

**Comment by Dawidoskyy** [comment]
0k. aczkolwiek jestem wielkim fanem projektu i czekam na v3.0 pozdrawiam z rodzinka

**Comment by Dawidoskyy** [comment]
Juz wiesz czy to jest do odpalenia na kliencie samp czy potrzebujesz pomocy?
